spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/docum_db
    username: step
    password: pets
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update